name: Develop CI
on:

  pull_request:
      branches:
        - master
      paths-ignore:
        - README.md
        - .gitignore
        - .npmignore
jobs:
  # 任务ID
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 官方action，将代码拉取到虚拟机
      - name: Checkout  ️ 
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: |
           pnpm install
      - name: Build
        run: | 
           npm run build